[workspace]
resolver = "2"

members = [
    "y-sweet",
    "y-sweet-core",
]

exclude = [
    "y-sweet-worker",
]

[patch.crates-io]
yrs-kvstore = { git = "https://github.com/rbtying/yrs-persistence" }

