on:
  pull_request:
    branches: [ "*" ]
    paths:
      - "crates/**"

name: Clippy check
jobs:
  check-rust-clippy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates

    steps:
      - uses: actions/checkout@v4
      - name: Install latest rust toolchain
        run: rustup update && rustup component add clippy && rustup target add wasm32-unknown-unknown
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path=crates/Cargo.toml
