name: Integration Tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/integration-tests.yml"
      - "tests/**"
      - "crates/**"
      - "js-pkg/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  integration-test:
    runs-on: ubuntu-latest-16-cores
    container: ghcr.io/jamsocket/cicd-runner-base:main

    steps:
    - uses: actions/checkout@v4
    - name: Install latest rust toolchain
      run: rustup update && rustup default stable
    - name: Install client
      run: npm ci
      working-directory: js-pkg/client
    - name: Test deps
      run: npm ci
      working-directory: tests
    - name: Run integration tests
      run: npm test
      working-directory: tests
      timeout-minutes: 4

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-data
        path: tests/out
